version: '3.7'

services:

  osquery:
    image: "dactiv/osquery:4.1.2-ubuntu18.04"
    command:
      - osqueryd 
      - --flagfile=/etc/osquery/osquery.flags 
      - --tls_hostname=${fleet-host.docker.internal:8412}
    volumes:
      - ./files/osquery.flags:/etc/osquery/osquery.flags
      - ./files/fleet.crt:/etc/osquery/fleet.crt
    environment:
      - ENROLL_SECRET

  fleet:
    image: kolide/fleet:latest
    command: 
      - sh 
      - -c 
      - "/usr/bin/fleet prepare db --no-prompt && /usr/bin/fleet serve"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./data/fleet_logs:/logs
      - ./files/fleet.crt:/fleet/osquery/fleet.crt
      - ./files/fleet.key:/fleet/osquery/fleet.key
    ports:
      - "8412:8412"
    environment:
      ENROLL_SECRET: enroll
      KOLIDE_MYSQL_ADDRESS: mysql:3306
      KOLIDE_MYSQL_DATABASE: fleet
      KOLIDE_MYSQL_USERNAME: fleet
      KOLIDE_MYSQL_PASSWORD: fleet
      KOLIDE_REDIS_ADDRESS: redis:6379
      KOLIDE_SERVER_ADDRESS: 0.0.0.0:8412
      KOLIDE_AUTH_JWT_KEY: ee7a11YpwcSQSwkazFdxq10AIvr2EzXE
      KOLIDE_SERVER_CERT: /fleet/osquery/fleet.crt
      KOLIDE_SERVER_KEY: /fleet/osquery/fleet.key
      KOLIDE_LOGGING_JSON: 'true'
      KOLIDE_OSQUERY_STATUS_LOG_PLUGIN: filesystem
      KOLIDE_FILESYSTEM_STATUS_LOG_FILE: /logs/osqueryd.status.log
      KOLIDE_OSQUERY_RESULT_LOG_PLUGIN: filesystem
      KOLIDE_FILESYSTEM_RESULT_LOG_FILE: /logs/osqueryd.results.log
    
  redis:
    image: redis:3.2.4
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    volumes:
      - .:/data
    command: 
      - mysqld 
      - --datadir=/tmp/data
      - --slow_query_log=1
      - --log_output=TABLE
      - --log-queries-not-using-indexes
      - --event-scheduler=ON
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: fleet
      MYSQL_USER: fleet
      MYSQL_PASSWORD: fleet
    ports:
      - "3306:3306"
